import fs from "node:fs";
import path from "node:path";

export class WorkspaceActions {
  constructor(root) {
    this.root = root;
  }

  execute(roomId, brief) {
    const roomDir = path.join(this.root, safe(roomId));
    const mailDir = path.join(roomDir, "mailroom");
    const calendarDir = path.join(roomDir, "calendar");
    fs.mkdirSync(mailDir, { recursive: true });
    fs.mkdirSync(calendarDir, { recursive: true });

    const briefPath = path.join(roomDir, "meeting-brief.md");
    const tasksPath = path.join(roomDir, "tasks.json");
    const mailPath = path.join(mailDir, "follow-up.eml");
    const calendarPath = path.join(calendarDir, "governance-review.ics");

    fs.writeFileSync(briefPath, markdownBrief(brief));
    fs.writeFileSync(tasksPath, `${JSON.stringify(brief.commitments, null, 2)}\n`);
    fs.writeFileSync(mailPath, emailDraft(brief));
    fs.writeFileSync(calendarPath, calendarInvite(brief));

    return [
      artifact("Vault", "Meeting brief stored", "complete", briefPath),
      artifact("Tasks", `${brief.commitments.length} monitored commitment${brief.commitments.length === 1 ? "" : "s"} created`, "complete", tasksPath),
      artifact("Mailroom", "Follow-up drafted for internal attendees", "approval", mailPath),
      artifact("Calendar", "Friday governance review proposed", "approval", calendarPath),
    ];
  }

  monitor() {
    if (!fs.existsSync(this.root)) return { status: "watching", commitments: 0, rooms: 0 };
    const roomDirs = fs.readdirSync(this.root, { withFileTypes: true }).filter((entry) => entry.isDirectory());
    let commitments = 0;
    for (const room of roomDirs) {
      const filename = path.join(this.root, room.name, "tasks.json");
      if (!fs.existsSync(filename)) continue;
      try { commitments += JSON.parse(fs.readFileSync(filename, "utf8")).length; } catch {}
    }
    return { status: "watching", commitments, rooms: roomDirs.length, checkedAt: new Date().toISOString() };
  }
}

function markdownBrief(brief) {
  return [
    `# ${brief.title}`,
    "",
    `Created locally: ${brief.at}`,
    `Created by: ${brief.createdBy}`,
    "",
    "## Summary",
    brief.summary,
    "",
    "## Decisions",
    ...(brief.decisions.length ? brief.decisions.map((item) => `- ${item}`) : ["- No confirmed decisions."]),
    "",
    "## Commitments",
    ...(brief.commitments.length
      ? brief.commitments.map((item) => `- [ ] ${item.task} — ${item.owner}, ${item.due}`)
      : ["- None captured."]),
    "",
    "Generated by LocalRoom on the local Dell Pro. No cloud inference.",
    "",
  ].join("\n");
}

function emailDraft(brief) {
  const commitments = brief.commitments.map((item) =>
    `- ${item.task} — ${item.owner}, ${item.due}`).join("\n") || "- None";
  return [
    "From: localroom@rainforest.internal",
    "To: project-iliad@rainforest.internal",
    `Subject: ${brief.title}`,
    "X-LocalRoom-Status: DRAFT-REQUIRES-APPROVAL",
    "",
    brief.summary,
    "",
    "Commitments:",
    commitments,
    "",
    "Drafted locally by LocalRoom. Review before sending.",
    "",
  ].join("\r\n");
}

function calendarInvite(brief) {
  const stamp = brief.at.replace(/[-:]/g, "").replace(/\.\d{3}Z$/, "Z");
  return [
    "BEGIN:VCALENDAR", "VERSION:2.0", "PRODID:-//LocalRoom//Private Meeting Agent//EN",
    "BEGIN:VEVENT", `UID:${brief.id}@localroom.internal`, `DTSTAMP:${stamp}`,
    "SUMMARY:Project Iliad governance review",
    "DESCRIPTION:Review LocalRoom commitments and approved disclosures.",
    "STATUS:TENTATIVE", "END:VEVENT", "END:VCALENDAR", "",
  ].join("\r\n");
}

function artifact(service, label, status, filename) {
  return { service, label, status, localPath: filename };
}

function safe(value) {
  return String(value).replace(/[^a-z0-9_-]/gi, "-").slice(0, 80);
}
